module Packets
  enum ServerPacket : UInt16
    USER_ID = 5
    SEND_MESSAGE = 7
    PONG = 8
    USER_STATS = 11
    USER_PRESENCE = 83
    USER_LOGOUT = 12
    SPECTATOR_JOINED = 13
    SPECTATOR_LEFT = 14
    SPECTATE_FRAMES = 15
    VERSION_UPDATE = 19
    SPECTATOR_CANT_SPECTATE = 22
    NOTIFICATION = 24
    UPDATE_MATCH = 26
    NEW_MATCH = 27
    DISPOSE_MATCH = 28
    MATCH_JOIN_SUCCESS = 36
    MATCH_JOIN_FAIL = 37
    FELLOW_SPECTATOR_JOINED = 42
    FELLOW_SPECTATOR_LEFT = 43
    MATCH_START = 46
    MATCH_SCORE_UPDATE = 48
    MATCH_TRANSFER_HOST = 50
    MATCH_ALL_PLAYERS_LOADED = 53
    MATCH_PLAYER_FAILED = 57
    MATCH_COMPLETE = 58
    MATCH_SKIP = 61
    CHANNEL_JOIN = 64
    CHANNEL_INFO = 65
    CHANNEL_KICK = 66
    CHANNEL_AUTO_JOIN = 67
    PRIVILEGES = 71
    FRIENDS_LIST = 72
    MATCH_PLAYER_SKIPPED = 81
    RESTART = 86
    MATCH_INVITE = 88
    ACCOUNT_RESTRICTED = 104
    PROTOCOL_VERSION = 75
    CHANNEL_INFO_END = 89
    MATCH_CHANGE_PASSWORD = 91
    SILENCE_END = 92
    USER_SILENCED = 94
    USER_DM_BLOCKED = 100
    TARGET_IS_SILENCED = 101
    MATCH_ABORT = 106
  end

  alias TypeArg = Tuple

  enum OsuType
    I8; U8; I16; U16; I32; U32
    I64; U64; F32; F64
    String; I32List
    Message; Channel; Match; ScoreFrame
    Raw
  end
end
